### ISSUE TITLE
【設定】必要なGemを追加する。

### ISSUE THREAD

**Issue by tundes** [pan16/omise_app#3]
## 内容
アプリケーションに必要なGemを追加する。

### デバッグ系
* pry-rails
* pry-byebug'
* annotate

### 開発時に必要なもの
*  letter_opene  => 自動メール送信等をdevelop環境で確認できる

### アプリに必要なもの
* bootstrap-sass
* mini_racer

その他何かあったら入れていく。

**Comment by ghost** [comment]
OK

**Comment by tundes** [comment]
therubyracer
